<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/02/06 16:01:18

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=Blogmanagement',
  'username' => 'root',
  'password' => 12345,
  'name' => 'doctrine',
)),);
